nodejs-week3
Sana-Shabeel/meal-sharing pull request #1
Opened 2022-03-10 21:36 UTC by Sana-Shabeel

2022-03-14 21:02 UTC, miltonhultgren requested changes
Mostly this looks good, there are a few small things you could improve and one big one.
The big one is that your endpoints should be able to handle any combination of parameters.

Further, I'd put some thought into what actions in your code are expensive (hint: asking the database!). So make sure you do the cheap validation (input data) before you ask the database anything.

2022-03-14 21:02 UTC, miltonhultgren commented on src/backend/api/meals.js
> +// GET route all meals route
I would love to see the route definition and route handler separated.

```js
router.get("/", listMeals);

async function listMeals(req, res) => {
```

2022-03-14 21:02 UTC, miltonhultgren commented on src/backend/api/meals.js
> +        throw new Error();
Make sure you always include a message in your errors, so you know what went wrong.

2022-03-14 21:02 UTC, miltonhultgren commented on src/backend/api/meals.js
> +router.get("/", async (req, res) => {
This route should be able to handle a combination of any supported parameters.
Your code currently only support a subset mix and the "if based" code is fairly hard to follow.

How can you change this code so that it doesn't matter which parameters are passed in?
A combination of default parameter values and a combined knex query should be able to handle this in much less code!

2022-03-14 21:02 UTC, miltonhultgren commented on src/backend/api/meals.js
> +    const availableMeals = getMeals.filter(
I'm pretty sure you can get knex to perform this filter for you!

2022-03-14 21:02 UTC, miltonhultgren commented on src/backend/api/meals.js
> +  if (!validData) {
Perhaps isValidData should return two values instead:
`const [isValid, errors] = isValidData(req.body)`

As you perform each check, if one fails you add a string to the errors list and return the status at the end.

2022-03-14 21:02 UTC, miltonhultgren commented on src/backend/api/meals.js
> +  const checkedId = await knex("meal").where({ id: req.params.id });
I'd do the validity check before touching the database,

2022-03-15 09:37 UTC, miltonhultgren commented on src/backend/api/meals.js
> +router.get("/", async (req, res) => {
Also, review this comment about the usage of `if` https://github.com/negaren/hyf-homework/pull/19/files#r826736613

2022-03-15 09:40 UTC, Sana-Shabeel commented on src/backend/api/meals.js
> +router.get("/", async (req, res) => {
Are you saying there is a better way of handling the request.query without having to create an if statement for each and everyone of them ?

2022-03-15 10:13 UTC, miltonhultgren commented on src/backend/api/meals.js
> +router.get("/", async (req, res) => {
See https://github.com/negaren/meal-sharing/pull/1#discussion_r826793745 for more detials.

2022-03-15 10:43 UTC, miltonhultgren commented on src/backend/api/meals.js
> +router.get("/", async (req, res) => {
Yes.
By moving the logic that converts and validates your parameters (and using default values) you can simplify this handler by a lot. 
See the comments I've linked above for more details on how.

2022-03-17 19:10 UTC, merged